- Generally ML models developed by maths
- Covert categorical column to Numerical columns
- Here we are transform the data
- This method is called as **Encoding**
- Feature Analysis : first 5 sessions
- Feature Engineering : Transform the data
- Feature selection : Machine learning

- Before Model Development
- We will do EDA : Exploratry data analysis
    - Features(Columns) analysis
        - Categorical,NUmerical,Outlier analysis,Bivarient,Multivarient
        - We will get the insights
    - Feature Engineering
        - we will modify the data
        - MOdels developed by maths
        - Encoding : Convert categorical data to Numerical Variables
        - Scaling : All the  numerical column makes under one scale
        - Transformation : All the maths developed 
            - Convert skewed distribution to Normal
    - Feature selection

- map
- LabelEncoder
- OneHotEncoder

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

path="Visadataset.csv"
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [2]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
visa_df['case_status']

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

In [4]:
# Check how many unique values are vailable
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [5]:
# create a dictionary assign a number start with zero
# for each Labels based on alphabetical order
d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [6]:
# map the dictionary with column
visa_df['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [7]:
visa_df['case_status']=visa_df['case_status'].map(d)

In [8]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [9]:
path="Visadataset.csv"
visa_df=pd.read_csv(path)

visa_df['case_status'].unique()
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)

In [10]:
path="Visadataset.csv"
visa_df=pd.read_csv(path)

visa_df['case_status'].unique()
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)

In [11]:
labels=sorted(visa_df['continent'].unique())
d={}
for i in range(len(labels)):
    key=labels[i]
    d[key]=i
# Dictionary comprehension
d={labels[i]:i for i in range(len(labels))}   #i==number     i Labels[i]==value
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [12]:
path="Visadataset.csv"
visa_df=pd.read_csv(path)

labels=sorted(visa_df['continent'].unique())
d={labels[i]:i for i in range(len(labels))}   #i==number     i Labels[i]==value
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [13]:
path="Visadataset.csv"
visa_df=pd.read_csv(path)

cat=visa_df.select_dtypes(include='object').columns
for i in cat:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}   #i==number     i Labels[i]==value
    visa_df[i]=visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## Label Encoder

- package name : **sklearn**
    - class: ** preprocessing**
        - method: ** LabelEncoder**

- from sklearn.preprocessing import LabelEncoder

In [ ]:
- step-1: import the method

- step-2: save the method

- step-3: apply fit transform
    
**fit transform**
    
- fit :  finding something

    - first we are finding dictionary

- transform : change the data

    - using the dictionary we are changing Eng to Number

In [14]:
from sklearn.preprocessing import LabelEncoder
path="Visadataset.csv"
visa_df=pd.read_csv(path)

le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

In [15]:
from sklearn.preprocessing import LabelEncoder
path="Visadataset.csv"
visa_df=pd.read_csv(path)
le=LabelEncoder()
for i in cat:
    visa_df[i]=le.fit_transform(visa_df[i])

In [16]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## OneHotEncoder
- The method name is: pd.get_dummies

|case_status|case_status_Denied|case_status_Certified
|-|
|Denied|
|Certified|

In [17]:
# continent   Continent_aisa     continent_africa    continene_Europe

# asia            1                   0                    0

# africa         0                    1                     0

# Europe         0                    0                     1

In [18]:
path="Visadataset.csv"
visa_df=pd.read_csv(path)

pd.get_dummies(visa_df['continent'],
              dtype='int')

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [19]:
visa_df
visa_df['continent']
visa_df['continent'].values  # values get an array

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

In [20]:
# Task:
# how to create a all columns

## LabelEncoder Vs OneHotEncoder

- Generally we dont want a relation between input columns
- we need both input columns are not correlated each other
- we need both input columns are independent(X,y)
- we need input columns are perpendicular each other
- we need both input columns are Orthogonal each other
- we need both input columns are 90 degrees phase shift each other
- OneHotEncoder will achieve above
- But OneHotEncoder creates new columns
    - columns are incerase means dimenssions are increase
    - More dimension data need more processing time
    - More dimension data need more infra
    - THis is called Curse of Dimensionality