In [ ]:
======================= Data Analysis ==========================

1. Pandas                  : Data frame Analysis
2. Numpy                   : Numerical Analysis
3. matplotlib              : Graphs and plots
4. seaborn                 : plots
5. Bokhe                   : plots
6. plotly                  : plots

====================== Machine Learning ===========================

7. stats             : for statistical models
8. scikit-learn(sklearn):  ML models

====================== Deep learning ===============================
    
9. opencv       : computer vision
10. pillow      : Image operations
11. tensorflow  : Neutral Network creations(developed by google)
12. keras       : NN
13. pytorch     : alternative package of tensorflow(facebook meta)

========================== NLP ===================================

14. NLTK  : Natural Language Toolkit
15. SpaCy: Alternative to NLTK
16. wordcloud    :  most frequent occured words
    
=========================== Scarapping============================

17. SqLite       : Data base creation
18. Beautiful soup
19. Selenium

========================== API Creation ===========================

20. Flask
21. FastAPI
22. Gradio
23. Django

======================= UI app Creation ============================

24. Streamlit

======================== Transfer learning models (DL)==============

25. Mobilenet
26. Resnet
27. VGGnet
28. Inception
29. Yolo      :  Ultralytics

====================== Transfer learning models (NLP)==============
30. Word2vec
31. GloVe

===================== Huging Face Transformers =======================

32. BERT   : Bi Directional Encoder Reprensentation of Transformers

======================= Allen NLP ====================================
33. Allen NLP package

============================= GenAI ====================================
34. LangChain
35. Google GeminiAi related packages
36. OpenAI GPT related packages
37. Amazon BedRock related packages
38. Meta Llama related packages

========================= Image and Vedio Generations ======================
39. GAN models related packages
40. SORA related packages

========================== Model deployment (MlOps) ========================
41. mlflow using databricks
42. kubeflow (GCP account)

============================== Cloud applications =========================
43. Azure ML related packages
44. GCP VertexAI related packages
45. AWS Sagemaker related packages

============================ small ===============================
46. time
47. logging
48. math
49. random
50. env
51. os

### step-1: Import packages

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### step-2: create a Dataframe using list

- data : your data which is in list or dict format
  
- index : we need to provide a list

- column : we need to provide a list

In [4]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names)

        0
0  Ramesh
1  Suresh
2  Satish

In [5]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
             columns=['Names'])
# pd.DataFrame(data,index,columns)

    Names
0  Ramesh
1  Suresh
2  Satish

### step-3: change the index

In [6]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
            index=['A','B','C'],
            columns=['Names'])

    Names
A  Ramesh
B  Suresh
C  Satish

In [7]:
names=['Ramesh','Suresh','Satish']
idx=['A','B','C']
cols=['Names']
pd.DataFrame(names,
            index=idx,
            columns=cols)

    Names
A  Ramesh
B  Suresh
C  Satish

### step-4: Add multiple columns

In [8]:
names=['Ramesh','Suresh','Satish']
age=[20,22,24]
pd.DataFrame(zip(names,age),
             columns=['Names','Age'])

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

In [9]:
np.__version__

'2.1.3'

### step-5: Create empty dataframe and update the columns

In [10]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

### srep-6: Add a new column with existing dataframe

In [11]:
names=['Ramesh','Suresh','Satish']
age=[20,22,24]
pd.DataFrame(zip(names,age),
             columns=['Names','Age'])
df['City']=['Hyd','Pune','Blr']
df

    Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Satish   24   Blr

### step-7: overwrite the column values

- I want to overwrite my age values
- originally age is = [20,222,24]
- now i want to update the age = [30,32,34]

In [12]:
df['Age']=[30,32,34]
df

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [13]:
df['age']=[30,32,34]
df
# 4 th column appear:new column(small 'a')

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [14]:
df['Age']=[30,32,34]
df['age']=[30,32,34]
df

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

### step-8: Drop the column

- labels
- axis
- index
- column
- inplace

In [15]:
df

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [16]:
df.drop('age')   # error

# here pyhton assume age is a label
# python ask 1 more question: is it index label or column label
# axis=1 means fro column
# axis=0 means for rows
# by default axis=0

KeyError: "['age'] not found in axis"

In [ ]:
df.drop('age',axis=0) #error

In [17]:
df.drop('age',axis=1)  #correct

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [15]:
df # we are able to see old column
# because we did not apply inplace=True

    Names  Age  City  age
0  Ramesh   30   Hyd   30
1  Suresh   32  Pune   32
2  Satish   34   Blr   34

In [16]:
df.drop('age',
       axis=1)

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [17]:

df.drop(columns=['age'],
        inplace=True)

In [18]:
df

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [19]:
# drop index=2
df.drop(2,
       axis=0)

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune

In [20]:
df.drop(index=2)

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune

### srep-9: Rename the column

In [ ]:
mapper:dictionary{'City':'city'}
index:
columns:
axis:
copy:
inplace:

In [22]:
df
# I want to change City column: city

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [23]:
dict1={'City':'city'}
df.rename(dict1)

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [24]:
dict1={'City':'city'}
df.rename(dict1,axis=1)

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [25]:
dict1={'City':'city'}
df.rename(columns=dict1)

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [26]:
dict1={'City':'city'}
df.rename(columns=dict1,
          inplace=True)
df

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [27]:
dict1={'City':'city'}
df.rename(dict1,
          inplace=True)
df

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [28]:
dict1={'City':'city'}
df.rename(dict1,
          axis=1,
          inplace=True)
df

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
2  Satish   34   Blr

In [29]:
dict2={2:'B'}
df.rename(dict2,
         inplace=True)
df

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
B  Satish   34   Blr

In [30]:
dict1={2:'B'}
df.rename(index=dict1)

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
B  Satish   34   Blr

In [31]:
dict1={2:'B'}
df.rename(dict1,axis=0)

    Names  Age  city
0  Ramesh   30   Hyd
1  Suresh   32  Pune
B  Satish   34   Blr

In [32]:
df1=pd.DataFrame()
df1['value']=[i for i in range(1,10)]
df1['square_value']=[i**2 for i in range(1,10)]
df1['cube_value']=[i**3 for i in range(1,10)]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [ ]:
- len
- columns
- shape
- dtypes
- head
- tail

In [33]:
df1.columns

Index(['value', 'square_value', 'cube_value'], dtype='object')

In [34]:
list(df1.columns)

['value', 'square_value', 'cube_value']

In [35]:
df1.columns.to_list()

['value', 'square_value', 'cube_value']

In [36]:
df1.shape
# 9 rows 3 columns

(9, 3)

In [37]:
df1.dtypes
# for integer we will get integet
# for float we wiil get float
# for string we will get string

value           int64
square_value    int64
cube_value      int64
dtype: object

In [38]:
df1.head

<bound method NDFrame.head of    value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729>

In [39]:
df1.head(2)

   value  square_value  cube_value
0      1             1           1
1      2             4           8

In [40]:
len(df1)

9

In [41]:
df1.isnull()
# we are asking a qn
# a null valur available or not
# True or False
# Tu=rue means yes NUll available
# False means no NULL valur not available

   value  square_value  cube_value
0  False         False       False
1  False         False       False
2  False         False       False
3  False         False       False
4  False         False       False
5  False         False       False
6  False         False       False
7  False         False       False
8  False         False       False

In [42]:
df1.isnull().sum()
# column wise null value count will display

value           0
square_value    0
cube_value      0
dtype: int64

In [43]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   value         9 non-null      int64
 1   square_value  9 non-null      int64
 2   cube_value    9 non-null      int64
dtypes: int64(3)
memory usage: 348.0 bytes

In [44]:
df1.tail

<bound method NDFrame.tail of    value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729>

In [45]:
df1.tail(3)

   value  square_value  cube_value
6      7            49         343
7      8            64         512
8      9            81         729

### step-10:

- How to change A specific value of a column
- df1.drop
    - either it will drop column or index
- df1.rename
    - either it will rename column or index
- df1.replace

In [46]:
df1
# replace cube_value 64 to 464

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [47]:
df1.replace(to_replace=64,value=464)

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

In [48]:
df1.replace(46,464) # all the data will replace
df1.replace({64:646,1:111}) # all the data will replace

   value  square_value  cube_value
0    111           111         111
1      2             4           8
2      3             9          27
3      4            16         646
4      5            25         125
5      6            36         216
6      7            49         343
7      8           646         512
8      9            81         729

### step-11: Selection of a column

In [49]:
df1['cube_value']
# series 
# series looks like dataframe
# rows and column

0      1
1      8
2     27
3     64
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [50]:
type(df1)

pandas.core.frame.DataFrame

In [51]:
type(df1['cube_value'])

pandas.core.series.Series

In [52]:
df1.shape # 2D

(9, 3)

In [53]:
df1['cube_value'].shape
# 1D data

(9,)

In [54]:
df1[['cube_value']]

   cube_value
0           1
1           8
2          27
3          64
4         125
5         216
6         343
7         512
8         729

In [55]:
type(df1[['cube_value']])
df1[['cube_value']].shape

(9, 1)

In [56]:
# sqaure_value
# cube_value
# multiple always keep those in list
df1[['cube_value','square_value']]

   cube_value  square_value
0           1             1
1           8             4
2          27             9
3          64            16
4         125            25
5         216            36
6         343            49
7         512            64
8         729            81

In [57]:
df1['cube_value'].replace(64,464,inplace=True)

In [58]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

### step-12: How to append a row

- loc
- iloc

In [59]:
# df1.loc[rows,column]
# df1.iloc[rows,column]

# we can select particular rows and columns using a lists: [strt:stop:step]
df1.iloc[3:7]

# iloc for nuber
# loc for name

   value  square_value  cube_value
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343

In [60]:
df1.loc[3:7,['square_value','cube_value']]

   square_value  cube_value
3            16         464
4            25         125
5            36         216
6            49         343
7            64         512

In [61]:
cols=['square_value','cube_value']
df1.loc[3:7,cols]

   square_value  cube_value
3            16         464
4            25         125
5            36         216
6            49         343
7            64         512

In [62]:
df1.iloc[[2,3,4]]
df1.iloc[[2]]
df1.iloc[2]
df1.iloc[[2,3,4],[0,2]]
df1.iloc[2,0]
df1.iloc[:,0]
df1.iloc[2,:]
df1.iloc[[2],:]
df1.iloc[2:6,0]
df1.iloc[2:6,[0]]

   value
2      3
3      4
4      5
5      6

In [63]:
df1.iloc[[2,3,4]]

   value  square_value  cube_value
2      3             9          27
3      4            16         464
4      5            25         125

In [64]:
df1.iloc[[2]]  # 2D series

   value  square_value  cube_value
2      3             9          27

In [65]:
df1.iloc[2]  # 1D

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [66]:
df1.iloc[[2,3,4],[0,2]]
# 2,3,4 row
# 0 andn 2 index(1,3)

   value  cube_value
2      3          27
3      4         464
4      5         125

In [67]:
df1.iloc[2,0]

np.int64(3)

In [68]:
df1.iloc[:,0]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: value, dtype: int64

In [69]:
df1.iloc[2,:]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [70]:
df1.iloc[[2],:]

   value  square_value  cube_value
2      3             9          27

In [71]:
df1.iloc[2:6,0]

2    3
3    4
4    5
5    6
Name: value, dtype: int64

In [72]:
df1.iloc[2:6,[0]]

   value
2      3
3      4
4      5
5      6

### how to append a row

In [73]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [74]:
len(df1)

9

In [75]:
df1.loc[9]=[10,100,1000]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [76]:
ID=len(df1)
df1.loc[ID]=[10,100,1000]
df1

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

### step-13: How to save the dataframes

- we can save dataframes in 2 ways
- .csv
- .xlsx
- where I want to save : directory
- what the filename to save : filename
- what is the type of a file : extension
- different folder: "C:\Users\Akanksha\Documents\Naresh IT\Generative AI\data1.csv"
- different folder: "C:\Users\Akanksha\Documents\Naresh IT\Generative AI\data1.xlsv"
- same folder : "data1.csv" or "data1.xlsx"

In [77]:
csv_path=r"C:\Users\Akanksha\Documents\Naresh IT\Generative AI\data1.csv"
excel_path=r"C:\Users\Akanksha\Documents\Naresh IT\Generative AI\data1.xlsx"
df1.to_csv(csv_path)
df1.to_excel(excel_path)

In [78]:
csv_path=r"data1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path)
df1.to_excel(excel_path)

### step-14 : Read the data

In [79]:
csv_path=r"data1.csv"
pd.read_csv(csv_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16         464
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100        1000
10          10     10           100        1000

In [80]:
excel_path=r"data1.xlsx"
pd.read_excel(excel_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16         464
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100        1000
10          10     10           100        1000

In [81]:
csv_path=r"dat1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path,index=False)  # index column created extra
df1.to_excel(excel_path,index=False)

In [82]:
csv_path=r"data1.csv"
pd.read_csv(csv_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16         464
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100        1000
10          10     10           100        1000

In [88]:
visa_df=r"Visadataset.csv"
pd.read_csv(visa_df)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [87]:
bank_df=r"bank.csv"
pd.read_csv(bank_df)

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]