In [1]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Satish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [3]:
df.to_csv('data_missing.csv',index=False)

In [4]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [5]:
df1.dtypes

NameError: name 'df1' is not defined

In [ ]:
df.isnull()

In [6]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [7]:
df1.isnull().sum()

NameError: name 'df1' is not defined

## fillna

In [8]:
df.fillna(30)  # Not recomended

    Names   Age  City
0  Ramesh  30.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0    30
3      30  27.0   Hyd

In [9]:
df1.fillna(30)

NameError: name 'df1' is not defined

- the above one is we are filling randomly
- all the columns are filled with random number
- it is not a good approach because in a data we have different data types

In [10]:
df['Age'].fillna(30)

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [11]:
df.fillna('Hyd')

    Names   Age  City
0  Ramesh   Hyd  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     Hyd  27.0   Hyd

## What is the difference between np.nan and None

In [12]:
np.nan+5

nan

In [13]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [14]:
arr1=np.array[1,2,np.nan,3]
arr2=np.array[1,2,None,3]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [15]:
arr1

NameError: name 'arr1' is not defined

In [16]:
arr2

NameError: name 'arr2' is not defined

In [17]:
np.nansum(arr1),np.sum(arr1)

NameError: name 'arr1' is not defined

In [18]:
np.sum(arr2)

NameError: name 'arr2' is not defined

- np.nan represents float type
- None represents Object type
- if data operations related to Maths then nan format is better

## Fill the value based on column

In [19]:
# df.fillna()
df['Names'].fillna('Manish')

0    Ramesh
1    Suresh
2    Satish
3    Manish
Name: Names, dtype: object

## Fill with Methods

- whenever we are using methods no need to provide values

In [20]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suresh','Satish',np.nan],
     'Age':[np.nan,22,25,27],
     'City':['Pune','Pune',np.nan,'Hyd']}

df=pd.DataFrame(Data)
df

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

- pad
- bfill
- ffill
- backfill

In [21]:
df.fillna(method='pad')

C:\Users\Akanksha\AppData\Local\Temp\ipykernel_17032\196241153.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [22]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [23]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill')

    Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

In [24]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill')

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [25]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill')

    Names   Age  City
0  Ramesh  22.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   Hyd
3     NaN  27.0   Hyd

## Mean-Median-Mode
- instead of fillng with random values
- we can use mean median and mode also
- For Numerical columns use mean and Median
  - if data

In [26]:
age_median=df['Age'].median()
df['Age'].fillna(age_median)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [27]:
age_median

25.0

In [28]:
mode=df['City'].mode()
mode

0    Pune
Name: City, dtype: object

## KNN Immputer

- K- Nearest Neighbours
- Where k= hyper parameter which means the user can change
- Idea: Instead of taking all the samples average
    - First fix the neighbours number i.e.k
    - Then find the neighbours using distance metric
    - Then take the avarage of those samples to fill the missing value

digram and formula of hypotenus

In [30]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [33]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [ ]:
# Import method
# save method
# apply fit transform

In [34]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer = KNNImputer(n_neighbors=2,
                    weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [35]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer = KNNImputer(n_neighbors=2,
                    weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])